<?php
/**
 * Admin view for the List Bizerbuilders page.
 * Uses the Plugin_List_Table class to display the list of plugins.
 *
 * @package WP-Bizerbuilder
 * @since 1.0.0
 * @version 1.0.5
 * @link https://wp-bizerbuilder.com
 * @license GPL-2.0+
 * @license https://www.gnu.org/licenses/gpl-2.0.html
 */

namespace WP_Bizerbuilder;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Initialize the WP_List_Table class.
$plugin_list_table = new Admin\Plugin_List_Table();
$plugin_list_table->prepare_items();
$bizerbuilders = $plugin_list_table->get_plugins();
$no_plugins  = empty( $bizerbuilders );

?>
<div class="wrap">
	<h1>
		<?php esc_html_e( 'Bizerbuilders', 'wp-bizerbuilder' ); ?>
		<a href="<?php echo esc_url( admin_url( 'admin.php?page=wp-bizerbuilder-generate' ) ); ?>" class="page-title-action"><?php esc_html_e( 'Generate New Plugin', 'wp-bizerbuilder' ); ?></a>
	</h1>
	<?php
	if ( $no_plugins ) {
		// Show a clear message if there are no plugins, along with a button to generate a new plugin.
		?>
		<div class="wp-bizerbuilder-card">
			<h2><?php esc_html_e( 'You don\'t have any bizerbuilders yet.', 'wp-bizerbuilder' ); ?></h2>
			<p><?php esc_html_e( 'Bizerbuilders are regular plugins, but they are generated by AI. You can manage them just like any other plugin. They will be listed here for your convenience.', 'wp-bizerbuilder' ); ?></p>
			<a href="<?php echo esc_url( admin_url( 'admin.php?page=wp-bizerbuilder-generate' ) ); ?>" class="button button-primary button-hero"><?php esc_html_e( 'Generate New Plugin', 'wp-bizerbuilder' ); ?></a>
		</div>
		<?php
	} else {
		$plugin_list_table->display();
	}
	?>
</div>
